/**
 * NYC events dataset (crawled 2026-08-27) — real upcoming events sourced from
 * public listings on Resident Advisor, Dice, Eventbrite, Ticketmaster,
 * redeyeny.com, Posh and Ticket Tailor, covering tonight through Oct 31 2026.
 * (Tixr was skipped — no public city directory.)
 *
 * Consumed by scripts/seed-events.ts. Coordinates are approximate venue
 * locations (good enough for the browse map); descriptions are our own
 * wording and cite the source platform. All times are America/New_York (EDT,
 * UTC-4, valid through Oct 31 2026).
 */

export interface SeedVenue {
  slug: string; // email local-part + stable key
  name: string;
  neighborhood: string;
  address: string;
  lat: number;
  lng: number;
  venueType: string;
  capacity: number;
  genres: string[];
  description: string;
}

export interface SeedEvent {
  venue: string; // SeedVenue.slug
  title: string; // ≤ 80 chars — event name, sometimes with role tag
  role: string; // role_needed
  date: string; // YYYY-MM-DD (America/New_York)
  start: string; // HH:MM 24h local
  hours: number; // duration
  rate: number; // base_rate (flat for performance roles, hourly for service roles)
  tips?: boolean;
  age?: 18 | 21; // age_requirement (default 21 for club nights)
  description: string;
  source: string;
}

/**
 * Support-role gigs → the event they staff. Any gig title NOT in this map is
 * its own event (its title names the happening). Keys and values are exact
 * gig-title strings from EVENTS below; the importer groups by
 * (venue, parent title) and derives one `events` row per group.
 */
export const EVENT_PARENTS: Record<string, string> = {
  'Susanne Bartsch: ON TOP — Performers': 'Susanne Bartsch: ON TOP',
  'POWER UP — Glow Dancers': "POWER UP: NYC's Glow Party",
  'REGGAETON WAREHOUSE — VIP service': 'REGGAETON WAREHOUSE (21+)',
  'Day & Night — floor security': 'Chaos In The CBD, Joe Claussell, Floorplan [Day & Night]',
  'Day & Night — bar team': 'Chaos In The CBD, Joe Claussell, Floorplan [Day & Night]',
  'Socafest 2026 — event security': 'Socafest 2026',
  'SOLID GROOVES — VIP service': 'SOLID GROOVES New York',
  'Teletech New York — floor security': 'Teletech New York',
  'Flag Invasion — VIP service': 'International Flag Invasion — Labor Day',
  'Teksupport: Four Tet — security': 'Teksupport: Four Tet',
  'Teksupport: Four Tet — bar team': 'Teksupport: Four Tet',
  'SACRO by MESTIZA — performers': 'SACRO by MESTIZA',
  'September Standard Gala — photographer': 'The 2026 September Standard Gala',
  'DAY+NIGHT — door security': 'DAY+NIGHT: D.Dan, Freddy K + more',
  'Jada Kingdom Live — opening DJ': 'Jada Kingdom + Byron Messiah Live',
  'Jamie Jones — VIP service': 'Jamie Jones',
  'Honey Dijon Day & Night — performers': 'Honey Dijon: Day & Night',
  'Honey Dijon Day & Night — bar team': 'Honey Dijon: Day & Night',
  'LIBRA RISING — support DJ': 'LIBRA RISING: Aluna and More',
  'HI-LO — event security': 'HI-LO w. Rebūke & Guests',
  'City of Gods Festival — night one': 'City of Gods Festival',
  'City of Gods Festival — main stage': 'City of Gods Festival',
  'City of Gods Festival — bar team': 'City of Gods Festival',
  'Bassvictim Halloween — security': 'Bassvictim — Halloween',
  'Bassvictim Halloween — performers': 'Bassvictim — Halloween',
};

export const VENUES: SeedVenue[] = [
  { slug: 'nowadays', name: 'Nowadays', neighborhood: 'Ridgewood', address: '56-06 Cooper Ave, Ridgewood, NY', lat: 40.7059, lng: -73.9087, venueType: 'Club', capacity: 700, genres: ['House', 'Techno', 'Ambient'], description: 'Indoor/outdoor club and dance institution on the Ridgewood–Bushwick border. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'basement', name: 'BASEMENT', neighborhood: 'Maspeth', address: '52-19 Flushing Ave, Maspeth, NY', lat: 40.7146, lng: -73.9188, venueType: 'Club', capacity: 400, genres: ['Techno'], description: 'Dark, strict-door techno club beneath Knockdown Center. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'knockdown-center', name: 'Knockdown Center', neighborhood: 'Maspeth', address: '52-19 Flushing Ave, Maspeth, NY', lat: 40.715, lng: -73.9182, venueType: 'Warehouse venue', capacity: 3200, genres: ['House', 'Techno', 'Live'], description: 'Former glass factory turned flagship warehouse venue for day-to-night dance events. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'elsewhere', name: 'Elsewhere', neighborhood: 'Bushwick', address: '599 Johnson Ave, Brooklyn, NY', lat: 40.7093, lng: -73.9291, venueType: 'Club / music venue', capacity: 675, genres: ['Indie', 'Electronic'], description: 'Multi-room club and live venue with a rooftop, hall and loft. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'signal', name: 'Signal', neighborhood: 'East Williamsburg', address: '260 Meserole St, Brooklyn, NY', lat: 40.7079, lng: -73.9339, venueType: 'Club', capacity: 500, genres: ['Techno', 'House'], description: 'Warehouse-style club built around a serious sound system. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'silo', name: 'SILO Brooklyn', neighborhood: 'East Williamsburg', address: '90 Scott Ave, Brooklyn, NY', lat: 40.7115, lng: -73.9273, venueType: 'Club', capacity: 600, genres: ['Techno', 'Bass'], description: 'High-ceilinged club room known for techno and bass programming. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'le-bain', name: 'Le Bain', neighborhood: 'Meatpacking', address: '848 Washington St, New York, NY', lat: 40.7408, lng: -74.008, venueType: 'Rooftop club', capacity: 300, genres: ['House', 'Disco'], description: 'Rooftop discothèque at The Standard, High Line. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'mood-ring', name: 'Mood Ring', neighborhood: 'Bushwick', address: '1260 Myrtle Ave, Brooklyn, NY', lat: 40.6996, lng: -73.9277, venueType: 'Bar / club', capacity: 150, genres: ['Eclectic'], description: 'Astrology-themed bar with a busy DJ back room. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'h0l0', name: 'H0L0', neighborhood: 'Ridgewood', address: '1090 Wyckoff Ave, Queens, NY', lat: 40.7059, lng: -73.9113, venueType: 'Club', capacity: 200, genres: ['Techno', 'Experimental'], description: 'Intimate two-room spot for leftfield club music. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'bossa-nova', name: 'Bossa Nova Civic Club', neighborhood: 'Bushwick', address: '1271 Myrtle Ave, Brooklyn, NY', lat: 40.6997, lng: -73.9269, venueType: 'Club', capacity: 150, genres: ['House', 'Techno'], description: 'Tropical-tinged neighborhood dance bunker. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'jupiter-disco', name: 'Jupiter Disco', neighborhood: 'Bushwick', address: '1237 Flushing Ave, Brooklyn, NY', lat: 40.707, lng: -73.9245, venueType: 'Bar / club', capacity: 120, genres: ['Disco', 'Electro'], description: 'Sci-fi cocktail bar with nightly DJs. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'good-room', name: 'Good Room', neighborhood: 'Greenpoint', address: '98 Meserole Ave, Brooklyn, NY', lat: 40.7257, lng: -73.9515, venueType: 'Club', capacity: 400, genres: ['House', 'Disco'], description: 'Beloved Greenpoint club with a proper dance floor and Bad Room annex. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'public-records', name: 'Public Records', neighborhood: 'Gowanus', address: '233 Butler St, Brooklyn, NY', lat: 40.6798, lng: -73.9846, venueType: 'Listening bar / club', capacity: 350, genres: ['Ambient', 'House'], description: 'Hi-fi listening venue, restaurant and club. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'paragon', name: 'Paragon', neighborhood: 'Bushwick', address: '815 Broadway, Brooklyn, NY', lat: 40.6982, lng: -73.9366, venueType: 'Club', capacity: 350, genres: ['Techno', 'House'], description: 'Bushwick club from the Mood Ring team. Demo profile seeded from public event listings (alpha test data).' },
  { slug: '99-scott', name: '99 Scott', neighborhood: 'East Williamsburg', address: '99 Scott Ave, Brooklyn, NY', lat: 40.711, lng: -73.927, venueType: 'Event space', capacity: 800, genres: ['Electronic'], description: 'Industrial event space with garden, used for club shows and productions. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'brooklyn-storehouse', name: 'Brooklyn Storehouse', neighborhood: 'Brooklyn Navy Yard', address: 'Building 293, Brooklyn Navy Yard, Brooklyn, NY', lat: 40.702, lng: -73.972, venueType: 'Warehouse venue', capacity: 3000, genres: ['Electronic', 'Live'], description: 'Massive Navy Yard warehouse hosting headline electronic shows. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'creekside', name: 'Creekside — Under the K Bridge', neighborhood: 'Greenpoint', address: 'Under the K Bridge Park, Brooklyn, NY', lat: 40.7295, lng: -73.9425, venueType: 'Outdoor venue', capacity: 4000, genres: ['Electronic'], description: 'Open-air stage beneath the Kosciuszko Bridge. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'moma-ps1', name: 'MoMA PS1', neighborhood: 'Long Island City', address: '22-25 Jackson Ave, Queens, NY', lat: 40.7456, lng: -73.947, venueType: 'Museum courtyard', capacity: 2000, genres: ['Eclectic'], description: 'Museum courtyard, home of the Warm Up summer series. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'house-of-yes', name: 'House of Yes', neighborhood: 'Bushwick', address: '2 Wyckoff Ave, Brooklyn, NY', lat: 40.7066, lng: -73.9236, venueType: 'Club / theatre', capacity: 450, genres: ['House', 'Performance'], description: 'Circus-infused nightclub famous for themed spectaculars. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'terminal-5', name: 'Terminal 5', neighborhood: 'Midtown West', address: '610 W 56th St, New York, NY', lat: 40.7696, lng: -73.9925, venueType: 'Concert hall', capacity: 3000, genres: ['Live', 'R&B'], description: 'Three-level Manhattan concert hall. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'pacha-nyc', name: 'Pacha New York', neighborhood: 'Midtown West', address: '618 W 46th St, New York, NY', lat: 40.7637, lng: -73.9976, venueType: 'Club', capacity: 1500, genres: ['House', 'Tech House'], description: 'The legendary cherry logo, back in Manhattan. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'honeys', name: "Honey's", neighborhood: 'East Williamsburg', address: '93 Scott Ave, Brooklyn, NY', lat: 40.7112, lng: -73.927, venueType: 'Bar / venue', capacity: 150, genres: ['Eclectic'], description: 'Mead bar and DIY-spirited party room. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'mehanata', name: 'Mehanata Bar', neighborhood: 'Lower East Side', address: '113 Ludlow St, New York, NY', lat: 40.719, lng: -73.9881, venueType: 'Bar / club', capacity: 200, genres: ['International'], description: 'The Bulgarian Bar — anything-goes LES dance institution. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'union-pool', name: 'Union Pool', neighborhood: 'Williamsburg', address: '484 Union Ave, Brooklyn, NY', lat: 40.7134, lng: -73.9513, venueType: 'Bar / venue', capacity: 200, genres: ['Indie'], description: 'Former pool-supply store with a backyard stage and taco truck. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'saint-vitus', name: 'Saint Vitus Bar', neighborhood: 'Greenpoint', address: '1120 Manhattan Ave, Brooklyn, NY', lat: 40.7378, lng: -73.954, venueType: 'Music venue', capacity: 250, genres: ['Metal', 'Punk'], description: 'Greenpoint metal haven. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'deluxx-fluxx', name: 'Deluxx Fluxx', neighborhood: 'Lower East Side', address: '198 Allen St, New York, NY', lat: 40.7218, lng: -73.9892, venueType: 'Club', capacity: 200, genres: ['Hip-Hop', 'Party'], description: 'Neon arcade-styled basement party room. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'arlo-roof', name: 'Rooftop at Arlo Williamsburg', neighborhood: 'Williamsburg', address: '96 Wythe Ave, Brooklyn, NY', lat: 40.7221, lng: -73.9577, venueType: 'Rooftop', capacity: 200, genres: ['House'], description: 'Skyline rooftop with sunset DJ sessions. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'melrose-ballroom', name: 'The Melrose Ballroom', neighborhood: 'Astoria', address: '36-08 33rd St, Astoria, NY', lat: 40.7553, lng: -73.9296, venueType: 'Event hall', capacity: 1200, genres: ['Latin', 'EDM'], description: 'Multi-level Queens event hall. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'brooklyn-monarch', name: 'The Brooklyn Monarch', neighborhood: 'East Williamsburg', address: '23 Meadow St, Brooklyn, NY', lat: 40.7133, lng: -73.933, venueType: 'Music venue', capacity: 1000, genres: ['Latin', 'Electronic'], description: 'Warehouse-scale venue for Latin and electronic parties. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'red-eye-ny', name: 'Red Eye NY', neighborhood: 'Midtown West', address: '355 W 41st St, New York, NY', lat: 40.7568, lng: -73.9925, venueType: 'Bar / cabaret', capacity: 250, genres: ['Pop', 'Drag', 'Cabaret'], description: "Hell's Kitchen queer nightlife spot with drag, cabaret and club nights. Demo profile seeded from public event listings (alpha test data)." },
  { slug: 'harbor-nyc', name: 'Harbor NYC', neighborhood: 'Midtown West', address: '621 W 46th St, New York, NY', lat: 40.7641, lng: -73.9972, venueType: 'Club / rooftop', capacity: 600, genres: ['Hip-Hop', 'Caribbean'], description: 'Rooftop nightclub on the far west side. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'the-dl', name: 'The DL', neighborhood: 'Lower East Side', address: '95 Delancey St, New York, NY', lat: 40.7184, lng: -73.9884, venueType: 'Rooftop lounge', capacity: 500, genres: ['Hip-Hop', 'Caribbean'], description: 'Three-floor LES lounge with a rooftop. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'littlefield', name: 'Littlefield', neighborhood: 'Gowanus', address: '635 Sackett St, Brooklyn, NY', lat: 40.6812, lng: -73.9846, venueType: 'Venue', capacity: 300, genres: ['Eclectic'], description: 'Gowanus performance venue for parties, comedy and live shows. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'out-of-ordinary', name: 'Out of Ordinary', neighborhood: 'Flatiron', address: 'Flatiron District, New York, NY', lat: 40.7411, lng: -73.9897, venueType: 'Lounge', capacity: 250, genres: ['R&B'], description: 'Flatiron cocktail lounge with R&B nights. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'brooklyn-steel', name: 'Brooklyn Steel', neighborhood: 'East Williamsburg', address: '319 Frost St, Brooklyn, NY', lat: 40.7166, lng: -73.9394, venueType: 'Concert venue', capacity: 1800, genres: ['Live', 'Indie', 'Electronic'], description: 'Steel-fabrication warehouse turned marquee concert room. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'amazura', name: 'Amazura', neighborhood: 'Jamaica', address: '91-12 144th Pl, Jamaica, NY', lat: 40.7022, lng: -73.8033, venueType: 'Concert hall', capacity: 3000, genres: ['Dancehall', 'Reggae'], description: 'Queens concert hall, home of major dancehall and reggae shows. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'beauty-bar', name: 'Beauty Bar', neighborhood: 'East Village', address: '231 E 14th St, New York, NY', lat: 40.7327, lng: -73.986, venueType: 'Bar', capacity: 100, genres: ['Comedy', 'Party'], description: 'Vintage-salon bar with comedy and DJ nights. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'brooklyn-museum', name: 'Brooklyn Museum', neighborhood: 'Prospect Heights', address: '200 Eastern Pkwy, Brooklyn, NY', lat: 40.6712, lng: -73.9636, venueType: 'Museum', capacity: 2000, genres: ['Soca', 'Culture'], description: 'Museum grounds hosting festival-scale cultural events. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'westlight', name: 'Westlight at The William Vale', neighborhood: 'Williamsburg', address: '111 N 12th St, Brooklyn, NY', lat: 40.7221, lng: -73.9573, venueType: 'Rooftop bar', capacity: 250, genres: ['Melodic House'], description: '22nd-floor rooftop bar with skyline views. Demo profile seeded from public event listings (alpha test data).' },
  { slug: '74wythe', name: '74Wythe', neighborhood: 'Williamsburg', address: '74 Wythe Ave, Brooklyn, NY', lat: 40.7217, lng: -73.9583, venueType: 'Rooftop event space', capacity: 400, genres: ['Hip-Hop', 'House'], description: 'Rooftop event space on the Williamsburg waterfront blocks. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'hidden-wonders', name: 'Hidden Wonders Showroom', neighborhood: 'Midtown', address: 'Theater District, New York, NY', lat: 40.759, lng: -73.9845, venueType: 'Speakeasy theatre', capacity: 80, genres: ['Magic', 'Variety'], description: 'Speakeasy-style magic showroom near Times Square. Demo profile seeded from public event listings (alpha test data).' },
  { slug: '1-hotel-bk', name: "Harriet's at 1 Hotel Brooklyn Bridge", neighborhood: 'Dumbo', address: '60 Furman St, Brooklyn, NY', lat: 40.7023, lng: -73.9954, venueType: 'Hotel rooftop', capacity: 200, genres: ['House'], description: 'Rooftop lounge overlooking the East River and skyline. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'industry-city', name: 'Industry City', neighborhood: 'Sunset Park', address: '220 36th St, Brooklyn, NY', lat: 40.6559, lng: -74.0083, venueType: 'Event complex', capacity: 5000, genres: ['Festival'], description: 'Waterfront maker campus hosting festival-scale events. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'fulton-fish', name: 'The Fulton Fish Market', neighborhood: 'Seaport', address: 'South Street Seaport, New York, NY', lat: 40.7063, lng: -74.0022, venueType: 'Warehouse venue', capacity: 2500, genres: ['Tech House'], description: 'Seaport warehouse space used for large dance events. Demo profile seeded from public event listings (alpha test data).' },
  { slug: '314-scholes', name: '314 Scholes', neighborhood: 'East Williamsburg', address: '314 Scholes St, Brooklyn, NY', lat: 40.7093, lng: -73.9396, venueType: 'Loft venue', capacity: 300, genres: ['House'], description: 'Loft venue for community-rooted dance parties. Demo profile seeded from public event listings (alpha test data).' },
  { slug: 'sva-theatre', name: 'SVA Theatre', neighborhood: 'Chelsea', address: '333 W 23rd St, New York, NY', lat: 40.7451, lng: -74.0005, venueType: 'Theatre', capacity: 480, genres: ['Live', 'Comedy'], description: 'Chelsea theatre hosting live shows and screenings. Demo profile seeded from public event listings (alpha test data).' },
];

export const EVENTS: SeedEvent[] = [
  // ── Thu Aug 27 (tonight) ────────────────────────────────────────────────
  { venue: 'nowadays', title: 'Body Hack: umru, ARCHANGEL + more', role: 'DJ', date: '2026-08-27', start: '22:00', hours: 6, rate: 400, age: 21, description: 'Club night with umru, ARCHANGEL, Clit.hub, Saintclair, Ivy Fischer, Quetamine and swello. Peak-slot DJ set on the main floor. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'elsewhere', title: 'Rival Consoles (Live)', role: 'DJ', date: '2026-08-27', start: '21:00', hours: 4, rate: 350, age: 18, description: 'Live electronic show in the Hall; we need a support DJ to open and close the room. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'signal', title: 'Pregame: 2001, Auphoria b2b Armii1n, DJ Brian', role: 'DJ', date: '2026-08-27', start: '23:00', hours: 5, rate: 250, age: 21, description: 'Warehouse pregame session with Auphoria b2b Armii1n and DJ Brian. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'silo', title: 'Techno Thursday [Melodic2Hard]', role: 'DJ', date: '2026-08-27', start: '22:00', hours: 6, rate: 200, age: 21, description: 'Weekly main-room techno night, melodic to hard. Free with RSVP for the crowd; booth needs a closing DJ. Listed publicly on Resident Advisor and Dice.', source: 'ra.co + dice.fm' },
  { venue: 'le-bain', title: 'Susanne Bartsch: ON TOP', role: 'DJ', date: '2026-08-27', start: '22:00', hours: 5, rate: 300, age: 21, description: 'Susanne Bartsch’s legendary rooftop party with Miss Parker and planetperris. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'le-bain', title: 'Susanne Bartsch: ON TOP — Performers', role: 'Go-Go Dancer', date: '2026-08-27', start: '22:00', hours: 5, rate: 275, age: 21, description: 'Looks-forward performance slots for the ON TOP rooftop party. Costume encouraged, two stage sets. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'mood-ring', title: 'DISCHARGE: Communion', role: 'DJ', date: '2026-08-27', start: '22:00', hours: 5, rate: 180, age: 21, description: 'Back-room club night with KLKÉ, Homotopies, masha latte, Sam Valle and more. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'h0l0', title: 'Nuvé: Summer Never Ends', role: 'DJ', date: '2026-08-27', start: '22:00', hours: 5, rate: 200, age: 21, description: 'Summer closer with SKY JETTA and Dana Lu. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'bossa-nova', title: 'DAYTONA 500 Birthday Bash', role: 'DJ', date: '2026-08-27', start: '22:00', hours: 5, rate: 150, age: 21, description: 'Birthday takeover with Asha, DJ Warning, August V.M. and guests. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'jupiter-disco', title: 'Taj + DJ Practice', role: 'DJ', date: '2026-08-27', start: '22:00', hours: 5, rate: 150, age: 21, description: 'Night flight with Taj plus an open practice slot. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'mehanata', title: 'CLÜBSESSION pARTy after dark', role: 'DJ', date: '2026-08-27', start: '22:00', hours: 6, rate: 150, age: 21, description: 'Late session with Kasey Cortez and DJanae at the Bulgarian Bar. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'arlo-roof', title: 'Palosanto on the Roof', role: 'DJ', date: '2026-08-27', start: '17:00', hours: 5, rate: 250, age: 21, description: 'Sunset organic-house session on the rooftop. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: '1-hotel-bk', title: "Kaz James at Harriet's Rooftop", role: 'DJ', date: '2026-08-27', start: '17:00', hours: 5, rate: 400, age: 21, description: 'Rooftop headline session with Kaz James; warm-up and closing support needed. Sourced from a public listing on Posh.', source: 'posh.vip' },
  { venue: 'red-eye-ny', title: 'Drag, Occasionally.', role: 'Drag Performer', date: '2026-08-27', start: '19:00', hours: 3, rate: 200, age: 21, description: 'Early-evening drag revue; one featured guest spot open. Sourced from the venue’s public calendar at redeyeny.com.', source: 'redeyeny.com' },
  { venue: 'hidden-wonders', title: 'Hidden Wonders Speakeasy Magic', role: 'Bartender', date: '2026-08-27', start: '19:00', hours: 3, rate: 45, tips: true, age: 21, description: 'Craft-cocktail service during an intimate speakeasy magic show. Sourced from a public listing on Ticket Tailor.', source: 'tickettailor.com' },

  // ── Fri Aug 28 ──────────────────────────────────────────────────────────
  { venue: 'moma-ps1', title: 'Warm Up: TDJ, De Schuurman, keiyaA + more', role: 'DJ', date: '2026-08-28', start: '15:00', hours: 6, rate: 300, age: 18, description: 'Courtyard series date with TDJ, De Schuurman, keiyaA and DJ WORKING CLASS; opening-slot DJ wanted. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'signal', title: 'Night & Day: Eli Escobar, The Carry Nation + more', role: 'DJ', date: '2026-08-28', start: '22:00', hours: 8, rate: 350, age: 21, description: 'Marathon with Eli Escobar, The Carry Nation, Dee Diggs, Arvin T b2b Sissies of Mercy. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'h0l0', title: 'SHEILA', role: 'DJ', date: '2026-08-28', start: '22:00', hours: 5, rate: 180, age: 21, description: 'Friday-night club session. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'nowadays', title: 'Vladimir Ivkovic All Night', role: 'Bartender', date: '2026-08-28', start: '22:00', hours: 8, rate: 40, tips: true, age: 21, description: 'All-night single-artist session indoors; extra bar coverage through close. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'brooklyn-steel', title: 'Citizen (16+) — Live', role: 'Security', date: '2026-08-28', start: '19:00', hours: 5, rate: 32, age: 18, description: 'Door and floor security for a sold-out-pace rock show. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'red-eye-ny', title: "POWER UP: NYC's Glow Party", role: 'DJ', date: '2026-08-28', start: '22:00', hours: 5, rate: 250, age: 21, description: 'Blacklight glow party on the main floor. Sourced from the venue’s public calendar at redeyeny.com.', source: 'redeyeny.com' },
  { venue: 'red-eye-ny', title: 'POWER UP — Glow Dancers', role: 'Go-Go Dancer', date: '2026-08-28', start: '22:00', hours: 4, rate: 200, age: 21, description: 'UV-reactive looks for the POWER UP glow party; two podium sets. Sourced from the venue’s public calendar at redeyeny.com.', source: 'redeyeny.com' },
  { venue: 'deluxx-fluxx', title: 'NOSTALGIA: Throwback Classic Night', role: 'DJ', date: '2026-08-28', start: '22:00', hours: 5, rate: 200, age: 21, description: 'New York vs Atlanta throwback sets in the arcade basement. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'silo', title: 'Benson / Adapter', role: 'DJ', date: '2026-08-28', start: '22:00', hours: 6, rate: 220, age: 21, description: 'Main-room double bill; local opener wanted. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: '99-scott', title: 'MARIE VAUNT', role: 'DJ', date: '2026-08-28', start: '22:00', hours: 5, rate: 300, age: 21, description: 'Main-room techno headline show; direct-support slot open. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'brooklyn-monarch', title: 'REGGAETON WAREHOUSE (21+)', role: 'DJ', date: '2026-08-28', start: '23:00', hours: 5, rate: 250, age: 21, description: 'Warehouse-scale reggaeton party. Sourced from a public listing on Posh.', source: 'posh.vip' },
  { venue: 'brooklyn-monarch', title: 'REGGAETON WAREHOUSE — VIP service', role: 'Bottle Server', date: '2026-08-28', start: '23:00', hours: 5, rate: 25, tips: true, age: 21, description: 'VIP table service for the reggaeton warehouse party. Sourced from a public listing on Posh.', source: 'posh.vip' },
  { venue: 'littlefield', title: 'DANCEHALL vs SOCA Summer Party', role: 'DJ', date: '2026-08-28', start: '23:00', hours: 5, rate: 220, age: 21, description: 'Sound-clash style dancehall vs soca night. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },

  // ── Sat Aug 29 ──────────────────────────────────────────────────────────
  { venue: 'basement', title: 'Saturday: Yonti, Jason Kendig b2b James Axon + more', role: 'DJ', date: '2026-08-29', start: '23:00', hours: 7, rate: 450, age: 21, description: 'Saturday program with Yonti, Beste Hira, Annie Lew, Jason Kendig b2b James Axon, Kilopatrah Jones and Immy. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'knockdown-center', title: 'Chaos In The CBD, Joe Claussell, Floorplan [Day & Night]', role: 'DJ', date: '2026-08-29', start: '14:00', hours: 12, rate: 600, age: 21, description: 'Day-and-night program across the Ruins and main hall with Chaos In The CBD, Joe Claussell and Floorplan. Listed publicly on Resident Advisor and Dice (tickets from $38).', source: 'ra.co + dice.fm' },
  { venue: 'knockdown-center', title: 'Day & Night — floor security', role: 'Security', date: '2026-08-29', start: '13:00', hours: 13, rate: 32, age: 21, description: 'Perimeter and floor coverage for the Chaos In The CBD / Floorplan day-to-night event. Listed publicly on Resident Advisor and Dice.', source: 'ra.co + dice.fm' },
  { venue: 'knockdown-center', title: 'Day & Night — bar team', role: 'Bartender', date: '2026-08-29', start: '13:30', hours: 12, rate: 40, tips: true, age: 21, description: 'High-volume bar shifts across two bars for the day-to-night program. Listed publicly on Resident Advisor and Dice.', source: 'ra.co + dice.fm' },
  { venue: 'nowadays', title: 'Nonstop: Voices From The Lake (Live) + more', role: 'DJ', date: '2026-08-29', start: '22:00', hours: 8, rate: 400, age: 21, description: 'Nonstop program with Leeon, LOKA, MCMLXXXV, Ne/Re/A, Solofan and Voices From The Lake live. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'signal', title: 'Luar presents: ALEXIS DE LA ROSA + more', role: 'Go-Go Dancer', date: '2026-08-29', start: '23:00', hours: 5, rate: 250, age: 21, description: 'Fashion-house club night with ALEXIS DE LA ROSA, MORENXXX, Sevyn Love and Bobby Beethoven; runway-adjacent performance slots. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'brooklyn-steel', title: 'Virtual Riot and Blanke (18+)', role: 'Photographer', date: '2026-08-29', start: '21:00', hours: 4, rate: 275, age: 18, description: 'Pit and crowd coverage for a bass-heavy 18+ show; edited selects within 48h. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'red-eye-ny', title: 'GOLDILOXX', role: 'Drag Performer', date: '2026-08-29', start: '21:00', hours: 3, rate: 200, age: 21, description: 'Saturday drag showcase; one guest performer slot. Sourced from the venue’s public calendar at redeyeny.com.', source: 'redeyeny.com' },
  { venue: 'deluxx-fluxx', title: 'MAMACITA: Latin/Hip-Hop Party', role: 'DJ', date: '2026-08-29', start: '22:00', hours: 5, rate: 200, age: 21, description: 'Latin and hip-hop party in the basement. Sourced from a public listing on Dice.', source: 'dice.fm' },

  // ── Sun Aug 30 ──────────────────────────────────────────────────────────
  { venue: 'nowadays', title: 'Mister Sunday: Eamon Harkin All Day', role: 'Bartender', date: '2026-08-30', start: '13:00', hours: 7, rate: 40, tips: true, age: 21, description: 'Backyard day-party bar shifts for the Mister Sunday institution. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'beauty-bar', title: 'Standup Comedy Night', role: 'Bartender', date: '2026-08-30', start: '20:00', hours: 4, rate: 35, tips: true, age: 21, description: 'Bar coverage for the free Sunday comedy show. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },

  // ── Wed Sep 2 / Thu Sep 3 ───────────────────────────────────────────────
  { venue: 'red-eye-ny', title: 'HEDDA LETTUCE: Dressing on the Side', role: 'Drag Performer', date: '2026-09-02', start: '20:00', hours: 3, rate: 250, age: 21, description: 'Supporting spot for Hedda Lettuce’s one-queen show. Sourced from the venue’s public calendar at redeyeny.com.', source: 'redeyeny.com' },
  { venue: 'red-eye-ny', title: 'The Season: 93-94', role: 'DJ', date: '2026-09-03', start: '20:00', hours: 4, rate: 180, age: 21, description: '90s-era themed night; vinyl-friendly booth. Sourced from the venue’s public calendar at redeyeny.com.', source: 'redeyeny.com' },
  { venue: 'red-eye-ny', title: 'GOAT by Headero', role: 'Bartender', date: '2026-09-03', start: '21:00', hours: 4, rate: 40, tips: true, age: 21, description: 'Bar shift for the GOAT party. Sourced from the venue’s public calendar at redeyeny.com.', source: 'redeyeny.com' },
  { venue: 'the-dl', title: 'PULSE PARADISE — Carnival Kick Off', role: 'DJ', date: '2026-09-03', start: '18:00', hours: 6, rate: 250, age: 21, description: 'Labor Day carnival kick-off across the rooftop; soca and dancehall sets. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },

  // ── Labor Day weekend Sep 4–7 ───────────────────────────────────────────
  { venue: 'brooklyn-museum', title: 'Socafest 2026', role: 'DJ', date: '2026-09-04', start: '20:00', hours: 6, rate: 350, age: 18, description: 'Carnival-week soca festival on the museum grounds. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'brooklyn-museum', title: 'Socafest 2026 — event security', role: 'Security', date: '2026-09-04', start: '19:00', hours: 7, rate: 30, age: 18, description: 'Crowd management for Socafest on the museum grounds. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'deluxx-fluxx', title: 'Dutty After Dark (LDW Edition)', role: 'DJ', date: '2026-09-04', start: '23:00', hours: 5, rate: 200, age: 21, description: 'Labor Day weekend dancehall session. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'fulton-fish', title: 'SOLID GROOVES New York', role: 'DJ', date: '2026-09-05', start: '14:00', hours: 10, rate: 500, age: 21, description: 'Tech-house day rave at the Seaport warehouse; local support slot alongside the touring lineup. Sourced from a public listing on Dice (tickets from $87).', source: 'dice.fm' },
  { venue: 'fulton-fish', title: 'SOLID GROOVES — VIP service', role: 'Bottle Server', date: '2026-09-05', start: '15:00', hours: 9, rate: 25, tips: true, age: 21, description: 'VIP table service for SOLID GROOVES. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'knockdown-center', title: 'Hot Since 82 w/ Danny Tenaglia', role: 'DJ', date: '2026-09-05', start: '14:00', hours: 10, rate: 300, age: 21, description: 'Day-and-night bill with Hot Since 82, Danny Tenaglia, Juliet Mendoza and Kilopatrah Jones; opening-room DJ wanted. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'public-records', title: 'Wine For Me', role: 'DJ', date: '2026-09-05', start: '17:00', hours: 5, rate: 250, age: 21, description: 'Natural-wine garden session with hi-fi selectors. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'terminal-5', title: 'R&B ONLY LIVE', role: 'Photographer', date: '2026-09-05', start: '20:00', hours: 4, rate: 300, age: 18, description: 'Stage and crowd photography for the R&B ONLY live show. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'knockdown-center', title: 'Horse Meat Disco NY — Labor Day Weekender', role: 'DJ', date: '2026-09-06', start: '16:00', hours: 8, rate: 400, age: 21, description: 'The London disco institution’s Labor Day party; local warm-up slot. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'brooklyn-storehouse', title: 'Teletech New York', role: 'DJ', date: '2026-09-06', start: '14:00', hours: 10, rate: 350, age: 18, description: 'Hard-techno production at the Navy Yard warehouse; opening slot. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'brooklyn-storehouse', title: 'Teletech New York — floor security', role: 'Security', date: '2026-09-06', start: '13:00', hours: 11, rate: 34, age: 18, description: 'Floor and egress coverage for a 3,000-cap warehouse show. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'union-pool', title: 'SUMMER THUNDER: Heavy Blanket + CRICKETS', role: 'Bartender', date: '2026-09-06', start: '15:00', hours: 6, rate: 35, tips: true, age: 21, description: 'Free backyard matinee with Heavy Blanket (J Mascis) and CRICKETS; patio bar shift. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'saint-vitus', title: 'Converge + L.O.T.I.O.N.', role: 'Security', date: '2026-09-06', start: '19:00', hours: 5, rate: 30, age: 18, description: 'Show security for a heavy bill at the metal bar. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: '99-scott', title: 'Elsewhere Presents: DJ LEX & Friends Outdoors', role: 'DJ', date: '2026-09-06', start: '16:00', hours: 6, rate: 280, age: 18, description: 'Outdoor Sunday session in the yard. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'harbor-nyc', title: 'International Flag Invasion — Labor Day', role: 'DJ', date: '2026-09-06', start: '23:00', hours: 5, rate: 300, age: 21, description: 'Carnival Sunday rooftop fete. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'harbor-nyc', title: 'Flag Invasion — VIP service', role: 'Bottle Server', date: '2026-09-06', start: '23:00', hours: 5, rate: 25, tips: true, age: 21, description: 'Table service for the Labor Day rooftop fete. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'harbor-nyc', title: 'Reggae Superstar Armani — Labor Day', role: 'DJ', date: '2026-09-07', start: '18:00', hours: 6, rate: 300, age: 21, description: 'Labor Day Monday reggae showcase. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },

  // ── Sep 11–13 ───────────────────────────────────────────────────────────
  { venue: 'harbor-nyc', title: 'A Boogie & DJ Clue Night', role: 'Photographer', date: '2026-09-11', start: '23:00', hours: 4, rate: 250, age: 21, description: 'Celebrity-night coverage; fast turnaround selects for socials. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'knockdown-center', title: 'UNREAL x RUSH: Day & Night', role: 'DJ', date: '2026-09-12', start: '14:00', hours: 12, rate: 380, age: 21, description: 'Day-to-night hard-dance program; local support across two rooms. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'brooklyn-steel', title: 'Aldous Harding — Live', role: 'Bartender', date: '2026-09-12', start: '20:00', hours: 4, rate: 38, tips: true, age: 18, description: 'Bar shift for a seated-energy sold-out-pace show. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'sva-theatre', title: 'Drop Your Buffs: The Live Show!', role: 'Photographer', date: '2026-09-12', start: '19:30', hours: 3, rate: 250, age: 18, description: 'Stage photography for a live taping in Chelsea. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'brooklyn-steel', title: 'Sunset Rollercoaster (16+)', role: 'Security', date: '2026-09-13', start: '19:30', hours: 4, rate: 30, age: 18, description: 'Door and floor security for the Sunset Rollercoaster show. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'brooklyn-steel', title: 'Bella Kay (16+)', role: 'Photographer', date: '2026-09-16', start: '20:00', hours: 4, rate: 225, age: 18, description: 'Pit photography for the Bella Kay show. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },

  // ── Fri Sep 18 – Sun Sep 20 ─────────────────────────────────────────────
  { venue: 'basement', title: 'Mama Snake, Katie Rex, Gabrielle Kwarteng + more', role: 'DJ', date: '2026-09-18', start: '23:00', hours: 7, rate: 400, age: 21, description: 'Friday program with Mama Snake, Anabel Arroyo, Katie Rex, Fafi Abdel Nour, Gabrielle Kwarteng and Jek. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'brooklyn-storehouse', title: 'Teksupport: Four Tet', role: 'DJ', date: '2026-09-18', start: '21:00', hours: 6, rate: 350, age: 18, description: 'Second added Four Tet show; direct-support DJ slot. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'brooklyn-storehouse', title: 'Teksupport: Four Tet — security', role: 'Security', date: '2026-09-18', start: '20:00', hours: 7, rate: 35, age: 18, description: 'Floor security for a full-capacity warehouse headline show. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'brooklyn-storehouse', title: 'Teksupport: Four Tet — bar team', role: 'Bartender', date: '2026-09-18', start: '20:00', hours: 7, rate: 42, tips: true, age: 18, description: 'High-volume bar shifts for the Four Tet show. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'creekside', title: 'SACRO by MESTIZA', role: 'DJ', date: '2026-09-18', start: '17:00', hours: 6, rate: 250, age: 18, description: 'Open-air ritual-styled production under the K Bridge with MËSTIZA and Apache; opening DJ wanted. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'creekside', title: 'SACRO by MESTIZA — performers', role: 'Go-Go Dancer', date: '2026-09-18', start: '17:00', hours: 6, rate: 275, age: 18, description: 'Choreographed performance slots for the SACRO open-air production. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'paragon', title: 'OOMFCON 1 Year Anniversary', role: 'DJ', date: '2026-09-18', start: '22:00', hours: 6, rate: 250, age: 21, description: 'Anniversary night with BODYHACK, BIAS and KI-HOLE crews. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'elsewhere', title: 'Dublon, Arianna Danae', role: 'DJ', date: '2026-09-18', start: '22:00', hours: 5, rate: 250, age: 18, description: 'Club-floor double bill; local opener wanted. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'nowadays', title: 'Thinner Groove: Powder, 5ive, CZ Wang', role: 'DJ', date: '2026-09-18', start: '22:00', hours: 6, rate: 300, age: 21, description: 'Label night with Powder, 5ive and CZ Wang. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: '99-scott', title: 'Nitefreak presents HiNDE', role: 'Bottle Server', date: '2026-09-18', start: '22:00', hours: 5, rate: 25, tips: true, age: 21, description: 'VIP service for the HiNDE afro-house showcase. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'signal', title: 'Night & Day Weekender: CCL, Buttechno + more', role: 'DJ', date: '2026-09-18', start: '22:00', hours: 8, rate: 320, age: 21, description: 'Weekender opener with DJ Sundae, Buttechno, Konduku, CCL and more. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'good-room', title: 'Eli Escobar & Eternal Love All Night', role: 'DJ', date: '2026-09-18', start: '22:00', hours: 6, rate: 350, age: 21, description: 'Two rooms, two all-night residents; Bad Room support slot. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'knockdown-center', title: 'DJ Harvey (Extended Set) + Lovie', role: 'DJ', date: '2026-09-18', start: '21:00', hours: 7, rate: 300, age: 21, description: 'Extended-set night with DJ Harvey and Lovie; warm-up DJ wanted. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'h0l0', title: 'ReSolute x Aionia: Lena Willikens', role: 'DJ', date: '2026-09-18', start: '23:00', hours: 7, rate: 300, age: 21, description: 'ReSolute session with Lena Willikens, Mona Matsuoka and Athena. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'silo', title: 'Machine Thirst: Bollmann / Firebunny', role: 'DJ', date: '2026-09-18', start: '23:00', hours: 6, rate: 250, age: 21, description: 'Industrial techno night. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'public-records', title: 'Midgar: upsammy, OK EG (Live)', role: 'DJ', date: '2026-09-18', start: '21:00', hours: 5, rate: 300, age: 21, description: 'Sound-room bill with upsammy, Kamran Sadeghi and OK EG live. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'westlight', title: 'Friends In High Places: Nils Hoffmann', role: 'DJ', date: '2026-09-18', start: '20:00', hours: 5, rate: 350, age: 21, description: '22nd-floor melodic-house session with Nils Hoffmann. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'mood-ring', title: 'oomfRAVE presents: Lizdek', role: 'DJ', date: '2026-09-18', start: '22:00', hours: 5, rate: 180, age: 21, description: 'Internet-rave back room with Lizdek and friends. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'honeys', title: 'Everlit (Kardnl)', role: 'DJ', date: '2026-09-18', start: '21:00', hours: 5, rate: 150, age: 21, description: 'Bar-room club night. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: '74wythe', title: 'The 2026 September Standard Gala', role: 'Bartender', date: '2026-09-18', start: '20:00', hours: 5, rate: 45, tips: true, age: 21, description: 'Rooftop gala bar service. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: '74wythe', title: 'September Standard Gala — photographer', role: 'Photographer', date: '2026-09-18', start: '20:00', hours: 5, rate: 275, age: 21, description: 'Event photography for the rooftop gala. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'brooklyn-steel', title: 'ADELA (16+)', role: 'Security', date: '2026-09-18', start: '20:00', hours: 4, rate: 32, age: 18, description: 'Show security, first of two ADELA nights. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'basement', title: 'DAY+NIGHT: D.Dan, Freddy K + more', role: 'DJ', date: '2026-09-19', start: '14:00', hours: 12, rate: 450, age: 21, description: 'Day-to-night program with D.Dan, Mos, Elle Dee, Freddy K, RonLikeHell, cotton and more. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'basement', title: 'DAY+NIGHT — door security', role: 'Security', date: '2026-09-19', start: '13:00', hours: 13, rate: 35, age: 21, description: 'Door team for the strict-entry day-to-night marathon. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'nowadays', title: "Let's Dance Brooklyn x UPLIFTED", role: 'DJ', date: '2026-09-19', start: '17:00', hours: 7, rate: 280, age: 18, description: 'Season 13 kick-off, back-2-skool edition. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: '314-scholes', title: 'The Carry Nation: They Went On Forever', role: 'DJ', date: '2026-09-20', start: '22:00', hours: 6, rate: 300, age: 21, description: 'Loft marathon with The Carry Nation. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'brooklyn-steel', title: 'Dying Fetus w/ Sanguisugabogg', role: 'Security', date: '2026-09-20', start: '18:30', hours: 5, rate: 34, age: 18, description: 'Pit-heavy death-metal bill; experienced barricade crew. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },

  // ── Sep 25 – Oct 3 ──────────────────────────────────────────────────────
  { venue: 'amazura', title: 'Jada Kingdom + Byron Messiah Live', role: 'Security', date: '2026-09-25', start: '21:00', hours: 5, rate: 32, age: 18, description: 'Venue security for a headline dancehall show with Jada Kingdom, Byron Messiah and Trinidad Killa. Sourced from a public listing on Eventbrite (tickets from $50).', source: 'eventbrite.com' },
  { venue: 'amazura', title: 'Jada Kingdom Live — opening DJ', role: 'DJ', date: '2026-09-25', start: '21:00', hours: 5, rate: 250, age: 18, description: 'Warm-up dancehall selector before the headline sets. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'brooklyn-steel', title: 'Bikini Kill (16+)', role: 'Photographer', date: '2026-09-25', start: '20:00', hours: 4, rate: 275, age: 18, description: 'Pit photography for the Bikini Kill show. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'elsewhere', title: 'Takuya Nakamura: Cosmic Jungle', role: 'DJ', date: '2026-09-25', start: '22:30', hours: 5, rate: 250, age: 18, description: 'Loft session blending live trumpet and club sounds. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'melrose-ballroom', title: 'PLAYGRND SERIES NYC', role: 'DJ', date: '2026-10-03', start: '22:00', hours: 5, rate: 300, age: 21, description: 'Main-room house series; local support slot. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'elsewhere', title: 'Riria, SHAKING, Clearcast', role: 'DJ', date: '2026-10-03', start: '22:30', hours: 5, rate: 250, age: 18, description: 'Late-night triple bill in the loft. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },

  // ── Fri Oct 9 – Sun Oct 11 ──────────────────────────────────────────────
  { venue: 'good-room', title: 'RA25: New York City', role: 'DJ', date: '2026-10-09', start: '22:00', hours: 6, rate: 350, age: 21, description: 'Resident Advisor’s 25th-anniversary NYC stop. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'h0l0', title: 'ReSolute: Aurora Halal + Shvili', role: 'DJ', date: '2026-10-09', start: '23:00', hours: 7, rate: 300, age: 21, description: 'ReSolute session with Aurora Halal and Shvili. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: '99-scott', title: 'ARODES w. JUNO', role: 'DJ', date: '2026-10-09', start: '22:00', hours: 6, rate: 320, age: 21, description: 'Afro-house headline night; opening slot. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'paragon', title: 'Paradiso: The Carry Nation, Mike Servito', role: 'DJ', date: '2026-10-09', start: '22:00', hours: 6, rate: 300, age: 21, description: 'Paradiso with The Carry Nation, Mike Servito, Kim Anh and Sissies of Mercy. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'terminal-5', title: 'Overmono — Live', role: 'Security', date: '2026-10-09', start: '20:00', hours: 4, rate: 33, age: 18, description: 'Floor security for the Overmono live show. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'knockdown-center', title: 'RUSH presents: KETTAMA', role: 'DJ', date: '2026-10-09', start: '22:00', hours: 6, rate: 300, age: 21, description: 'Main-hall club show with KETTAMA; local support. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'pacha-nyc', title: 'Jamie Jones', role: 'DJ', date: '2026-10-09', start: '22:00', hours: 6, rate: 300, age: 21, description: 'Opening-room DJ for the Jamie Jones headline night. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'pacha-nyc', title: 'Jamie Jones — VIP service', role: 'Bottle Server', date: '2026-10-09', start: '22:00', hours: 6, rate: 28, tips: true, age: 21, description: 'VIP table service for the Jamie Jones night. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'honeys', title: 'VHS: Heavenly Delusion', role: 'DJ', date: '2026-10-09', start: '22:00', hours: 6, rate: 180, age: 21, description: 'VHS crew night with KYRUH, J.N.R., DJ girlcrush and more. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'westlight', title: 'Friends In High Places: Special Guests', role: 'DJ', date: '2026-10-09', start: '20:00', hours: 5, rate: 300, age: 21, description: 'Rooftop session with unannounced special guests. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'mehanata', title: 'The Y2K Party (18+)', role: 'DJ', date: '2026-10-09', start: '22:00', hours: 6, rate: 180, age: 18, description: 'Y2K-era throwback night. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'brooklyn-steel', title: 'Daði Freyr (16+)', role: 'Bartender', date: '2026-10-09', start: '20:00', hours: 4, rate: 38, tips: true, age: 18, description: 'Bar shift for the Daði Freyr show. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'knockdown-center', title: 'Honey Dijon: Day & Night', role: 'DJ', date: '2026-10-10', start: '14:00', hours: 12, rate: 600, age: 21, description: 'Honey Dijon’s day-to-night takeover. Listed publicly on Resident Advisor and Dice (tickets from $48).', source: 'ra.co + dice.fm' },
  { venue: 'knockdown-center', title: 'Honey Dijon Day & Night — performers', role: 'Go-Go Dancer', date: '2026-10-10', start: '16:00', hours: 8, rate: 250, age: 21, description: 'Podium performance slots for the Honey Dijon takeover. Listed publicly on Resident Advisor and Dice.', source: 'ra.co + dice.fm' },
  { venue: 'knockdown-center', title: 'Honey Dijon Day & Night — bar team', role: 'Bartender', date: '2026-10-10', start: '13:30', hours: 12, rate: 42, tips: true, age: 21, description: 'Bar coverage across the hall and Ruins bars. Listed publicly on Resident Advisor and Dice.', source: 'ra.co + dice.fm' },
  { venue: 'house-of-yes', title: 'LIBRA RISING: Aluna and More', role: 'Go-Go Dancer', date: '2026-10-10', start: '22:00', hours: 6, rate: 250, age: 21, description: 'Astrology-season spectacular with Aluna; aerial-adjacent performance slots. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'house-of-yes', title: 'LIBRA RISING — support DJ', role: 'DJ', date: '2026-10-10', start: '22:00', hours: 6, rate: 300, age: 21, description: 'Support DJ for the LIBRA RISING night with Aluna. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'creekside', title: 'HI-LO w. Rebūke & Guests', role: 'DJ', date: '2026-10-11', start: '16:00', hours: 7, rate: 280, age: 18, description: 'Open-air techno under the K Bridge with HI-LO and Rebūke; opening slot. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'creekside', title: 'HI-LO — event security', role: 'Security', date: '2026-10-11', start: '15:00', hours: 8, rate: 35, age: 18, description: 'Open-air event security for the HI-LO show. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'knockdown-center', title: 'GENESI & Guests', role: 'DJ', date: '2026-10-11', start: '16:00', hours: 8, rate: 280, age: 21, description: 'Sunday melodic-techno session; support slot. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'public-records', title: 'The Nursery: Frank & Tony, Roman Flügel', role: 'DJ', date: '2026-10-11', start: '17:00', hours: 6, rate: 300, age: 21, description: 'Sound-room Sunday with Frank & Tony and Roman Flügel. Sourced from a public listing on Resident Advisor.', source: 'ra.co' },
  { venue: 'brooklyn-steel', title: 'Tricky (16+)', role: 'Security', date: '2026-10-11', start: '20:00', hours: 4, rate: 33, age: 18, description: 'Show security for the Tricky date. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },

  // ── Mid/late Oct ────────────────────────────────────────────────────────
  { venue: 'brooklyn-steel', title: 'Cannons (16+)', role: 'Photographer', date: '2026-10-18', start: '20:00', hours: 4, rate: 250, age: 18, description: 'Pit photography for the Cannons show. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'industry-city', title: 'City of Gods Festival — night one', role: 'Security', date: '2026-10-23', start: '20:00', hours: 6, rate: 36, age: 18, description: 'Festival security, opening night of the three-day City of Gods run. Sourced from a public listing on Dice (tickets from $99).', source: 'dice.fm' },
  { venue: 'industry-city', title: 'City of Gods Festival — main stage', role: 'DJ', date: '2026-10-24', start: '20:00', hours: 6, rate: 350, age: 18, description: 'Undercard DJ slot on the City of Gods main stage. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'industry-city', title: 'City of Gods Festival — bar team', role: 'Bartender', date: '2026-10-25', start: '18:00', hours: 6, rate: 40, tips: true, age: 21, description: 'Closing-day bar shift for the festival. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'elsewhere', title: 'Big Crown Records 10 Year: El Michels Affair', role: 'Photographer', date: '2026-10-24', start: '18:00', hours: 5, rate: 300, age: 18, description: 'Label-anniversary show in the Hall with El Michels Affair and guests. Sourced from a public listing on Eventbrite.', source: 'eventbrite.com' },
  { venue: 'brooklyn-steel', title: 'Patrick Droney (16+)', role: 'Bartender', date: '2026-10-29', start: '20:00', hours: 4, rate: 38, tips: true, age: 18, description: 'Bar shift for the Patrick Droney show. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },
  { venue: 'brooklyn-steel', title: 'LAUNDRY DAY (16+)', role: 'Security', date: '2026-10-30', start: '20:00', hours: 4, rate: 33, age: 18, description: 'Show security for the LAUNDRY DAY date. Sourced from a public listing on Ticketmaster.', source: 'ticketmaster.com' },

  // ── Sat Oct 31 (Halloween) ──────────────────────────────────────────────
  { venue: 'knockdown-center', title: 'Bassvictim — Halloween', role: 'DJ', date: '2026-10-31', start: '22:00', hours: 7, rate: 400, age: 18, description: 'Halloween-night Bassvictim show; support DJ wanted. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'knockdown-center', title: 'Bassvictim Halloween — security', role: 'Security', date: '2026-10-31', start: '21:00', hours: 8, rate: 36, age: 18, description: 'Halloween floor security for the Bassvictim show. Sourced from a public listing on Dice.', source: 'dice.fm' },
  { venue: 'knockdown-center', title: 'Bassvictim Halloween — performers', role: 'Go-Go Dancer', date: '2026-10-31', start: '22:00', hours: 6, rate: 275, age: 21, description: 'Halloween costume performance slots. Sourced from a public listing on Dice.', source: 'dice.fm' },
];
